### PR TITLE
Apache 2.4

### PR DESCRIPTION
**Pull request by karpet**
This compiles and seems to pass its tests. There are still several non-fatal compile-time warnings.

### CODE REVIEW

**Comment by gavincarr** [comment]
Hi Peter,

Thanks for your patches, incorporated into the 2.3.99b1 beta.

Cheers,
Gavin

**Comment by vladsf** [comment]
I don't understand how this patch would not break other code chunks with 
#ifndef APACHE22
...
#else
clearly the build will be broken with only -DAPACHE24

Debian patch uses proper, universal call to identify which Apache version is used:
+#if AP_MODULE_MAGIC_AT_LEAST(20111130,0)

**Comment by gavincarr** [comment]
There were 3 sets of patches out there - Peter's, Ivo's/debian's, and Dietmar's. The 2.4 changes are are a blend of all 3, and do use AP_MODULE_MAGIC_AT_LEAST (check the code).

Cheers,
Gavin

**Comment by vladsf** [comment]
ah, I see now. good!

**Pull request closed without merging**
